In [3]:
import pandas as pd

In [5]:
df = pd.read_csv("notable_ai_models.csv")

In [10]:
df.columns

Index(['System', 'Domain', 'Organization', 'Authors', 'Publication date',
       'Reference', 'Link', 'Notability criteria', 'Notability criteria notes',
       'Parameters', 'Parameters notes', 'Training compute (FLOP)',
       'Training compute notes', 'Training dataset',
       'Training dataset size (datapoints)', 'Dataset size notes', 'Abstract',
       'Confidence', 'Epochs', 'Model accessibility',
       'Country (from Organization)', 'Organization categorization',
       'Training dataset notes', 'Training time (hours)',
       'Training time notes', 'Training hardware', 'Finetune compute notes',
       'Hardware quantity', 'Hardware utilization', 'Base model', 'Citations',
       'Compute cost notes', 'Finetune compute (FLOP)',
       'Training compute cost (2023 USD)', 'Batch size', 'Batch size notes'],
      dtype='object')

In [9]:
df

,System,Domain,Organization,Authors,Publication date,Reference,Link,Notability criteria,Notability criteria notes,Parameters,...,Finetune compute notes,Hardware quantity,Hardware utilization,Base model,Citations,Compute cost notes,Finetune compute (FLOP),Training compute cost (2023 USD),Batch size,Batch size notes
0,ESM3 (98B),Biology,"EvolutionaryScale,UC Berkeley","Thomas Hayes, Roshan Rao, Halil Akin, Nicholas...",2024-06-25,ESM3: Simulating 500 million years of evolutio...,https://www.evolutionaryscale.ai/blog/esm3-rel...,Historical significance,Largest (in compute) biology and protein model...,9.800000e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,DeepSeek-Coder-V2-236B,Language,DeepSeek,"Qihao Zhu, Daya Guo, Zhihong Shao, Dejian Yang...",2024-06-17,DeepSeek-Coder-V2: Breaking the Barrier of Clo...,https://github.com/deepseek-ai/DeepSeek-Coder-V2,SOTA improvement,"New SOTA on Aider, AIME 2024, and Math Odyssey...",2.360000e+11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Nemotron-4 340B,Language,NVIDIA,"Bo Adler, Niket Agarwal, Ashwath Aithal, Dong ...",2024-06-14,NVIDIA Releases Open Synthetic Data Generation...,https://blogs.nvidia.com/blog/nemotron-4-synth...,Training cost,"~2e25 FLOP, so high training cost, likely >5M",3.400000e+11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,GPT-4o,"Multimodal,Language,Audio,Speech,Vision",OpenAI,"Aidan Clark, Alex Paino, Jacob Menick, Liam Fe...",2024-05-13,Hello GPT-4o,https://openai.com/index/hello-gpt-4o/,"SOTA improvement,Significant use",Outperforms GPT-4 Turbo and other models on te...,NaN,...,"Definitely a new model, not a GPT-4 finetune",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Llama 3-70B,Language,Meta AI,Aaditya Singh; Aaron Grattafiori; Abhimanyu Du...,2024-04-18,Introducing Meta Llama 3: The most capable ope...,https://ai.meta.com/blog/meta-llama-3/,Significant use,Will almost certainly be very influential and ...,7.000000e+10,...,NaN,16000.0,0.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
820,Sequence-based pattern recognition,Vision,Massachusetts Institute of Technology (MIT),O. G. Selfridge,1955-03-01,Pattern recognition and modern computers,https://dl.acm.org/doi/10.1145/1455292.1455310,Historical significance,NaN,NaN,...,NaN,NaN,NaN,NaN,290.0,NaN,NaN,NaN,NaN,NaN
821,Self Organizing System,Other,Massachusetts Institute of Technology (MIT),W. A. Clark and B. G. Farley,1955-03-01,Generalization of pattern recognition in a sel...,https://dl.acm.org/doi/10.1145/1455292.1455309,Historical significance,NaN,2.250000e+02,...,NaN,NaN,NaN,NaN,93.0,NaN,NaN,NaN,NaN,NaN
822,Genetic algorithm,Other,Institute for Advanced Study,NA Barricelli,1954-07-02,Numerical testing of evolution theories,https://link.springer.com/article/10.1007/BF01...,Historical significance,Possibly first computer simulation of a geneti...,NaN,...,NaN,NaN,NaN,NaN,266.0,NaN,NaN,NaN,NaN,NaN
823,SNARC,Robotics,Harvard University,Marvin Minsky,1952-01-08,A Neural-Analogue Calculator Based upon a Prob...,https://en.wikipedia.org/wiki/Stochastic_neura...,Historical significance,NaN,4.000000e+01,...,NaN,NaN,NaN,NaN,33.0,NaN,NaN,NaN,NaN,NaN
824,Theseus,Robotics,Bell Laboratories,Claude Shannon,1950-07-02,Mighty Mouse,https://www.technologyreview.com/2018/12/19/13...,Historical significance,NaN,4.000000e+01,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN

In [8]:
df["System"]

0                              ESM3 (98B)
1                  DeepSeek-Coder-V2-236B
2                         Nemotron-4 340B
3                                  GPT-4o
4                             Llama 3-70B
                      ...
820    Sequence-based pattern recognition
821                Self Organizing System
822                     Genetic algorithm
823                                 SNARC
824                               Theseus
Name: System, Length: 825, dtype: object

In [11]:
df["Parameters"]

0      9.800000e+10
1      2.360000e+11
2      3.400000e+11
3               NaN
4      7.000000e+10
           ...
820             NaN
821    2.250000e+02
822             NaN
823    4.000000e+01
824    4.000000e+01
Name: Parameters, Length: 825, dtype: float64

In [13]:
df["Training compute (FLOP)"]

0      1.070000e+24
1      1.285200e+24
2      1.800000e+25
3               NaN
4      6.300000e+24
           ...
820             NaN
821             NaN
822             NaN
823             NaN
824    4.000000e+01
Name: Training compute (FLOP), Length: 825, dtype: float64

In [15]:
models = [
    "gpt-4",
    "claude-2",
    "claude",
    "gpt-3.5-turbo",
    "text-davinci-003",
    "claude-instant",
    "chat-bison-001",
    "text-davinci-002",
    "llama-2-70b",
    "guanaco-65b",
    "codellama-34b",
    "vicuna-33b",
    "wizardlm-30b",
    "guanaco-33b",
    "vicuna-13b",
    "llama-2-13b",
    "openchat-13b",
    "wizardlm-13b",
    "vicuna-7b",
    "codellama-13b",
    "codellama-7b",
    "koala-13b",
    "llama-2-7b",
    "codegeex2-6b",
    "dolly-12b",
    "chatglm-6b",
    "oasst-12b",
]

In [19]:
model_data = df[df["System"].transform(lambda x: x.lower()).isin(models)]

In [20]:
model_data

,System,Domain,Organization,Authors,Publication date,Reference,Link,Notability criteria,Notability criteria notes,Parameters,...,Finetune compute notes,Hardware quantity,Hardware utilization,Base model,Citations,Compute cost notes,Finetune compute (FLOP),Training compute cost (2023 USD),Batch size,Batch size notes
100,GPT-4,"Multimodal,Language,Vision,Image generation",OpenAI,"OpenAI, Josh Achiam, Steven Adler, Sandhini Ag...",2023-03-15,GPT-4 Technical Report,https://arxiv.org/abs/2303.08774,"Highly cited,SOTA improvement,Training cost","See the paper, p.1: ""On a suite of traditional...",NaN,...,NaN,25000.0,0.34,NaN,5290.0,NaN,NaN,4.058659e+07,NaN,NaN
102,Claude,Language,Anthropic,NaN,2023-03-14,Introducing Claude,https://www.anthropic.com/index/introducing-cl...,"Historical significance,SOTA improvement",NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN